import React, { Fragment, useState } from "react";
/* 
This is a game where the user guesses a four digit number generated by the computer.
 and tries to get the numbers in correct order.
 if the number is correct and in the right place  it turns green.
 if the number is correct but in the wong place it turns blue.
 if the number is wrong it turns red.


*/
export function NumberGuesser() {
  const [state, setState] = useState({
    randomNumber: [],
    guessedNumber: [],
    count: 0,
  });

  /*get  a four digit random number */
  function randomNumber() {
    let number = Math.floor(Math.random() * 9999);
    state.randomNumber = number.toString().split("");
    if (state.randomNumber.length === 4) {
      
    } else {
      randomNumber();
    }

    handleClick();
  }
  /* creating  event listeners  to get buttons ids that have been clicked*/
  function handleClick(e) {
    document.addEventListener("click", (e) => {
      return e.target.id;
    });
  }
  /* getting the users guess from the input fields*/
  function getGuess(e) {
    /* getting the value of each user guess*/
    let idList = [];
    for (let i = 0; i < 4; i++) {
      let ids = e.target.parentNode.childNodes[i].firstElementChild.id;
      idList.push(ids);
    }

    let guess1 = document.getElementById(idList[0]).value;
    let guess2 = document.getElementById(idList[1]).value;
    let guess3 = document.getElementById(idList[2]).value;
    let guess4 = document.getElementById(idList[3]).value;

    state.guessedNumber = [guess1, guess2, guess3, guess4];

    setState((prev) => ({
      ...prev,
      guessedNumber: state.guessedNumber,
    }));
    checkGuess();
  }
  /* checking if the user has guessed the correct number*/
  function checkGuess() {
    const guessedNumber = state.guessedNumber;
    const copyRandomNumber = state.randomNumber;
  
    if(state.guessedNumber.join() === state.randomNumber.join(',')){
      
      reveal()
    }
    /* checking if the user has guessed the correct number in correct position*/
    for (let i = 0; i < guessedNumber.length; i++) {
      if (guessedNumber[i] === copyRandomNumber[i]) {
        state.count = state.count - 1;
        setState((prev) => ({
          ...prev,
          count: state.count,
        }));
        let boxs = document.getElementById(state.count);
        boxs.style.backgroundColor = "green";
        /* checking if the user has guessed the correct number in the wrong place*/
      } else if (
        guessedNumber.indexOf([i]) !== copyRandomNumber[i] &&
        copyRandomNumber.includes(guessedNumber[i])
      ) {
        state.count = state.count - 1;
        setState((prev) => ({
          ...prev,
          count: state.count,
        }));
        let boxs = document.getElementById(state.count);
        boxs.style.backgroundColor = "blue";

        /*checking if user guessed a non used number*/
      } else if (
        guessedNumber[i] !== copyRandomNumber[i] &&
        copyRandomNumber.includes(guessedNumber[i]) === false
      ) {
        state.count = state.count - 1;
        setState((prev) => ({
          ...prev,
          count: state.count,
        }));
        let boxs = document.getElementById(state.count);
        boxs.style.backgroundColor = "red";
      }
    }
  
  }
  function reset() {
    window.location.reload();
  }
  function reveal() {
    let reveal = document.getElementById("numberReveal");
    console.log(reveal);
    reveal.innerText = " !!! CONGRATULATIONS !!! the number was... " +  state.randomNumber.join("");
  }

  return (
    <Fragment>
      <div className="numberGuesser">
        <h1>Number Guesser</h1>
        <div className="colorChart">
          <div className="red">Wrong number</div>
          <div className="green">Correct number</div>
          <div className="blue">Correct number but in the wrong place</div>
        </div>

        <div className="buttons">
          <button id="starter" onClick={randomNumber}>
            Start
          </button>{" "}
          <button id="reset" onClick={reset}>
            Restart
          </button>{" "}
        </div>
      

        <div id="guesses">
        <div id="numberReveal"></div>
          <div className="resultBox">
            <div className="result1" id="-1"></div>
            <div className="result2" id="-2"></div>
            <div className="result3" id="-3"></div>
            <div className="result4" id="-4"></div>
          </div>
          <div className="guessBox1">
            <div className="box-0">
              <input type="number" id="0" min="0" max="9" required />
            </div>
            <div className="box-1">
              {" "}
              <input type="number" id="1" min="0" max="9" required />{" "}
            </div>
            <div className="box-2">
              {" "}
              <input type="number" id="2" min="0" max="9" required />
            </div>
            <div className="box-3">
              {" "}
              <input type="number" id="3" min="0" max="9" required />
            </div>

            <button id="guessButton1" onClick={getGuess}>
              Check
            </button>
          </div>
          <div className="resultBox">
            <div className="result1" id="-5"></div>
            <div className="result2" id="-6"></div>
            <div className="result3" id="-7"></div>
            <div className="result4" id="-8"></div>
          </div>
          <div className="guessBox2">
            <div className="box-0">
              {""}
              <input type="number" id="11" min="0" max="9" required />
            </div>
            <div className="box-1">
              {" "}
              <input type="number" id="12" min="0" max="9" required />{" "}
            </div>
            <div className="box-2">
              {" "}
              <input type="number" id="13" min="0" max="9" required />
            </div>
            <div className="box-3">
              {" "}
              <input type="number" id="14" min="0" max="9" required />
            </div>

            <button id="guessButton2" onClick={getGuess}>
              Check
            </button>
          </div>

          <div className="resultBox">
            <div className="result1" id="-9"></div>
            <div className="result2" id="-10"></div>
            <div className="result3" id="-11"></div>
            <div className="result4" id="-12"></div>
          </div>
          <div className="guessBox3">
            <div className="box-0">
              <input type="number" id="17" min="0" max="9" required />
            </div>
            <div className="box-1">
              {" "}
              <input type="number" id="18" min="0" max="9" required />{" "}
            </div>
            <div className="box-2">
              {" "}
              <input type="number" id="19" min="0" max="9" required />
            </div>
            <div className="box-3">
              {" "}
              <input type="number" id="20" min="0" max="9" required />
            </div>

            <button id="guessButton3" onClick={getGuess}>
              Check
            </button>
          </div>
          <div className="resultBox">
            <div className="result1" id="-13"></div>
            <div className="result2" id="-14"></div>
            <div className="result3" id="-15"></div>
            <div className="result4" id="-16"></div>
          </div>
          <div className="guessBox4">
            <div className="box-0">
              <input type="number" id="21" min="0" max="9" required />
            </div>
            <div className="box-1">
              {" "}
              <input type="number" id="22" min="0" max="9" required />{" "}
            </div>
            <div className="box-2">
              {" "}
              <input type="number" id="23" min="0" max="9" required />
            </div>
            <div className="box-3">
              {" "}
              <input type="number" id="24" min="0" max="9" required />
            </div>{" "}
            <button id="guessButton4" onClick={getGuess}>
              Check
            </button>
          </div>
          <div className="resultBox">
            <div className="result1" id="-17"></div>
            <div className="result2" id="-18"></div>
            <div className="result3" id="-19"></div>
            <div className="result4" id="-20"></div>
          </div>
          <div className="guessBox5">
            <div className="box-0">
              <input type="number" id="25" min="0" max="9" required />
            </div>
            <div className="box-1">
              {" "}
              <input type="number" id="26" min="0" max="9" required />{" "}
            </div>
            <div className="box-2">
              {" "}
              <input type="number" id="27" min="0" max="9" required />
            </div>
            <div className="box-3">
              {" "}
              <input type="number" id="28" min="0" max="9" required />
            </div>{" "}
            <button id="guessButton5" onClick={getGuess}>
              Check
            </button>
          </div>
          <div className="resultBox">
            <div className="result1" id="-21"></div>
            <div className="result2" id="-22"></div>
            <div className="result3" id="-23"></div>
            <div className="result4" id="-24"></div>
          </div>
          <div className="guessBox6">
            <div className="box-0">
              <input type="number" id="29" min="0" max="9" required />
            </div>
            <div className="box-1">
              {" "}
              <input type="number" id="30" min="0" max="9" required />{" "}
            </div>
            <div className="box-2">
              {" "}
              <input type="number" id="31" min="0" max="9" required />
            </div>
            <div className="box-3">
              {" "}
              <input type="number" id="32" min="0" max="9" required />
            </div>{" "}
            <button id="guessButton6" onClick={getGuess}>
              Check
            </button>
          </div>
        </div>
      </div>
    </Fragment>
  );
}
